#Name: First Name Last Name
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Sharp
#Date:
#Project #: M10
#By submitting this assignment, I declare that the source code contained in this assignment was written s
#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i
#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, 
#Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un
#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv
#e a zero on this project if I am found in violation of this policy.

import csv # imports csv

FILENAME = "contacts.csv" # assaignes the name of the file we are using to FILENAME

def display_title(): # define the display_title function
    print("Parker Teeples Contact Manager App") # prints "Parker Teeples Contact Manager App"
    print() # print blank line
    
def display_menu(): # defines the diplay_menu function
    print("COMMAND MENU") # prints "COMMAND MENU"
    print() # prints blank line
    print("list - Display all contacts") # prints "list - Display all contacts"
    print("view - View a contact") # prints "view - View a contact"
    print("add - Add a contact") # prints "add - Add a contact"
    print("del - Delete a contact") # prints "del - Delete a contact"
    print("exit - Exit program") # prints "exit - Exit program"
    print() # prints a blank line

def main(): # define the main function
    contacts = read_contacts() # assaignes the variable contacts to the result of the function read_contacts
    display_title() # call the display_title function
    display_menu() # call the display_menu function
    while True: # while true loop
        command = input("Command: ") # command is set to the input of the user
        if command == "list": # if command is "list"
            display(contacts) # call the display function with the argument contacts
        elif command == "view": # if command is "view"
            view(contacts) # call the view function with the argument contacts
        elif command == "add": # if command is "add"
            add(contacts) # call the add function with the argument contacts
        elif command == "del": # if command is "del"
            delete(contacts) # call the delete function with the argument contacts
        elif command == "exit": # if command is "exit"
            break # break while loop
        else: # if none of the above
            print("Not a valid command. Please try again.\n") # print "Not a valid command. Please try again.\n"
    print("Bye!")

def read_contacts(): # define the read_contacts function
    contacts = [] # assaign contacts to an empty array
    try: # try following for errors
        with open(FILENAME, newline="") as file: # open the file and start a new line, as file
            reader = csv.reader(file) # set reader to file
            for row in reader: # for every row in file being read
                contacts.append(row) # append row to contacts
        return contacts # return contacts
    except FileNotFoundError: # if there is a FileNotFoundError
        print("Could not find contacts file! Starting new contacts file...") # print "Could not find contacts file! Starting new contacts file..."