#Name: Parker Teeples
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Tyler Bartholomew
#Date: 10/1/2024
#Project #: MO4_P1
#By submitting this assignment, I declare that the source code contained in this assignment was written s
#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i
#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, 
#Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un
#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv
#e a zero on this project if I am found in violation of this policy.

print("Parker Teeples's Letter Grade Converter") # Prints name of program
print() # prints blank line

choice = "y" # assaignes choice to 'y'

while choice.lower() == "y": # while choice is y it will loop
    number = int(input("Enter numerical grade: ")) # input for variable number
    if number >= 94: # if 94
        print("Letter grade: A") # print A
    elif number >= 90: # if over 90
        print("Letter grade: A-") # print A-
    elif number >= 87: # if over 87
        print("Letter grade: B+") # print B+
    elif number >= 84: # if over 84
        print("Letter grade: B") # print B
    elif number >= 80: # if over 80
        print("Letter grade: B-") # print B-
    elif number >= 77: # if over 77
        print("Letter grade: C+") # print C+
    elif number >= 74: # if over 74
        print("Letter grade: C") # print C
    elif number >= 70: # if over 70
        print("Letter grade: C-") # print C-
    elif number >= 67: # if over 67
        print("Letter grade: D+") # print D+
    elif number >= 64: # if over 64
        print("Letter grade: D") # print D
    elif number >= 60: # if over 60
        print("Letter grade: D-") # print D-
    elif number >= 0: # if over 0
        print("Letter grade: E") # print E
    else: # anything else
        print("Thats not a recognizable grade") # print Thats not a recognizable grade
    print() # print blank line
    choice = input("Continue? (y/n): ") # choice is set by input
    print() # print blank line
print("Bye!") # print bye
print() # print blank line