#Name: Parker Teeples
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Sharp
#Date:
#Project #: M03
#By submitting this assignment, I declare that the source code contained in this assignment was written s
#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i
#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, 
#Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un
#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv
#e a zero on this project if I am found in violation of this policy.

print("Parker Teeples Registration App") ## My registration app
print() ## empty line
first_name = input("First name: ") ## input first name
last_name  = input("Last name: ") ## input last name
birth_year = input("Birth year: ") ## input birth year
print() ## empty linr
print("Welcome " + str(first_name), str(last_name)) ## prints "Welcome" with the user's first and last name
print()
print("Your registration is complete") # print Your registration is complete
tempPassword = str(first_name) + "*" + str(birth_year) ## Combines first name, an *, and birth year into tempPassword
print("Your temporary password is: " + str(tempPassword)) ## Prints "Your temporary password is: tempPassword"