#Name: First Name Last Name
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Sharp
#Date:
#Project #: MO5_P1
#By submitting this assignment, I declare that the source code contained in this assignment was written s
#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i
#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, 
#Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un
#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv
#e a zero on this project if I am found in violation of this policy.

def is_even(num): # define the is_even function
    if num % 2 == 0: # if num divided by 2 has a no remainder
        return True # return true
    else: # if has remainder
        return False # return false

def main(): # define main function
    print("Parker Teeples Even or Odd Checker") # print project name
    print() # blank line
    my_num = int(input("Enter an integer: ")) # input an integer for my_num
    if is_even(my_num): # if my_num after is_even function is true
        print("This is an even number.") # print even
    else: # if false
        print("This is a odd number.") # pint is odd

if __name__ == "__main__": # name is main
    main() # call main