#Name: First Name Last Name
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: (Sharp)
#Date:
#Project #:
#By submitting this assignment, I declare that the source code contained in this assignment was written s
#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i
#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, 
#Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un
#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv
#e a zero on this project if I am found in violation of this policy.

firstName = 'Parker'
print('Hello, my name is ' + firstName)

school = 'Utah Valley University'
print('I go to ' + school)

credits = 3
classes = 6
totalcredits = credits * classes

print('If I take 6 classes this semester and all are three credits each I will be taking ' + str(totalcredits) + ' credits')

print('I would like to save money by taking this many credits.')

maxCredits = 12
costPerClass = 350
classFee = 20

totalCostPerSemester = ((totalcredits - maxCredits) / credits) * (costPerClass + classFee)

print('If classes are free after the ' + str(maxCredits) + ' credits and each class cost $' + str(costPerClass) + ' (plus an additional $' + str(classFee) + ' per class fee), I will be saving $' + str(totalCostPerSemester) + ' a semester.')

totalCostPerYear = totalCostPerSemester * 3

print('That is a wopping $' + str(totalCostPerYear) + ' a year!')

print('This was a very informative and worth while Python assignment!')
